### ISSUE TITLE
revisit fuzzy search

### ISSUE THREAD

**Issue by DavidRLowe** [NYPL/pic-app#101]
I'm afraid that in correcting for "Man Ray" we've lost "Brassaï". It again no longer recognizes accented or other special characters. I think we have to err on the side of people scrolling down to find the photog...

**Comment by mgiraldo** [comment]
probably need to include `preserve_original` in index, since the problem appears only if you search for the accented version: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html

see also: http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#analysis
