### ISSUE TITLE
Tweak to map point hover text

### ISSUE THREAD

**Issue by subsublibrary** [NYPL/pic-app#96]
This text:

n constituent(s) here

Make it:

n constituent(s) in [location]

e.g.

1 constituent in Poughkeepsie, NY, USA

or:

5 constituents in Turin, Italy

Would this work?

**Comment by mgiraldo** [comment]
we had a location and i decided to remove it because there is a significant delay between when you hover and when the location is shown... the location is determined with geonames and the api gets hammered if you move the mouse a lot. it can also take a couple of seconds to return so you see weird behavior in the text field (eg: you may get poughkeepsie but your mouse is already in hawaii)

**Comment by subsublibrary** [comment]
Got it. That makes sense.
